<?php

return [
    "AUD" => [
        "name" => "Australian Dollar",
        "symbol" => "$",
        "id" => "AUD",
        "location" => "left",
        "rate" => null,
    ],
    "AED" => [
        "name" => "United Arab Emirates dirham",
        "symbol" => "AED",
        "id" => "AED",
        "location" => "left",
        "rate" => 3.673,
    ],
    "BRL" => [
        "name" => "Brazilian Real",
        "symbol" => "R$",
        "id" => "BRL",
        "location" => "left",
        "rate" => null,
    ],
    "CAD" => [
        "name" => "Canadian Dollar",
        "symbol" => "$",
        "id" => "CAD",
        "location" => "left",
        "rate" => null,
    ],
    "CNY" => [
        "name" => "Chinese Yuan",
        "symbol" => "¥",
        "id" => "CNY",
        "location" => "left",
        "rate" => null,
    ],
    "EUR" => [
        "name" => "Euro",
        "symbol" => "€",
        "id" => "EUR",
        "location" => "right",
        "rate" => null,
    ],
    "GBP" => [
        "name" => "Pound sterling",
        "symbol" => "£",
        "id" => "GBP",
        "location" => "left",
        "rate" => null,
    ],
    "INR" => [
        "name" => "Indian Rupee",
        "symbol" => "₹",
        "id" => "INR",
        "location" => "left",
        "rate" => null,
    ],
    "JPY" => [
        "name" => "Japanese yen",
        "symbol" => "¥",
        "id" => "JPY",
        "location" => "left",
        "rate" => null,
    ],
    "MXN" => [
        "name" => "Mexican peso",
        "symbol" => "$",
        "id" => "MXN",
        "location" => "left",
        "rate" => null,
    ],
    "SGD" => [
        "name" => "Singapore dollar",
        "symbol" => "S$",
        "id" => "SGD",
        "location" => "left",
        "rate" => null,
    ],
    "USD" => [
        "name" => "United States Dollar",
        "symbol" => "$",
        "id" => "USD",
        "location" => "left",
        "rate" => null,
    ],
];
